---
title: "ggcor"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  fig.align = "center",
  out.width = "100%"
)
```

The goal of `ggcor` is to provide a set of functions that can be used to visualize a correlation matrix quickly.

## Installation

Now `ggcor` is not on cran, You can install it with:

``` r

# install.packages("devtools")
devtools::install_github("houyunhuang/ggcor")

```
## Correlation plot

```{r example01}
library(ggplot2)
library(ggcor)
set_scale()
quickcor(mtcars) + 
  geom_circle2()
quickcor(mtcars, type = "upper") + 
  geom_circle2()
quickcor(mtcars, cor.test = TRUE) +
  geom_circle2(data = get_data(type = "lower", show.diag = FALSE)) +
  geom_mark(data = get_data(type = "upper", show.diag = FALSE), 
            size = 2.5) +
  geom_abline(slope = -1, 
              intercept = 12)
```

## Mantel test plot

```{r example03, message=FALSE, warning=FALSE, echo=TRUE}
pacman::p_load(tidyverse, ggcor, yarrr)
data("varechem", package = "vegan")
data("varespec", package = "vegan")

mantel <- mantel_test(varespec, varechem,
                      spec.select = list(M1 = 1:7,
                                         M2= 8:18,
                                         M3 = 19:37,
                                         M4 = 38:44)) %>% 
  add_column(., rd = ifelse(abs(.$r)>=0.4, ">= 0.4", NA)) %>% 
  mutate(., rd = ifelse(abs(.$r)<0.4, "0.2 - 0.4", .$rd)) %>% 
  mutate(., rd = ifelse(abs(.$r)<0.2, "< 0.2", .$rd)) %>%
  add_column(., pd = ifelse(.$r > 0, "Positive", "Negative")) %>% 
  mutate(., pd = ifelse(.$p.value > 0.05, "ns", pd))

extra.params <- extra_params(
  env.point = point_params(colour = "#595959", fill = "#595959", size = 2),
  spec.point = point_params(colour = "#595959", fill = "#595959", size = 2),
  link.params = link_params(spec.point.hjust = 3),
  spec.label = text_params(size = 5))

colour_transparent <- transparent("white", 1)

quickcor(varechem, type = "upper", cor.test = T, method = "spearman", show.diag = F) +
  ### colour circles instead of the whole cell
  geom_circle2(colour = colour_transparent) +
  ### show stars in signif cells
  geom_mark(sig.thres = 0.05,
            color = "white",
            fontface = "bold",
            mark = c("*", "**", "***"),
            size = 5,
            r = NA,
            vjust = 0.75) +
  ### add correlations with lines
  add_link(df = mantel, 
           mapping = aes(colour = pd, size = rd),
           extra.params = extra.params,
           curvature = F) +
  ### cross-out non-significant cells
  # geom_cross(sig.level = 0.05, colour = "#8c8c8c", alpha = 0.5) +
  ### ggplot2 options
  scale_size_manual(values = c(0.5, 1, 2)) +
  scale_colour_manual(values = c("Positive" = "#29a649", "Negative" = "#d67600", "ns" = "grey80")) +
  scale_fill_gradient2(low = "#2d69ab", 
                       mid = "white", 
                       high = "#b42c3a", 
                       breaks = c(-1, -0.5, 0, 0.5, 1), 
                       limits = c(-1, 1)) +
  guides(size = guide_legend(title = "Mantel's r",
                             override.aes = list(colour = "grey35"), 
                             order = 2),
         colour = guide_legend(title = "Significance", 
                               override.aes = list(size = 3), 
                               order = 1),
         fill = guide_colourbar(title = "Spearman's r", 
                                order = 3)) +
  theme(axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13),
        text = element_text(size = 13),
        legend.key=element_blank()) 

```